# Generated by Django 2.1.4 on 2018-12-26 03:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181226_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='starting_date',
            field=models.DateField(default=datetime.datetime(2018, 12, 26, 3, 17, 16, 926286, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
