# Generated by Django 2.1.4 on 2018-12-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_course_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ending_date',
            field=models.DateField(default='2019-12-01'),
            preserve_default=False,
        ),
    ]
