# Generated by Django 2.1.4 on 2018-12-27 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20181227_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logintype',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginType',
        ),
    ]
